CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER(10) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(250) NOT NULL,
    IMAGEM CLOB,
    MARCA VARCHAR2(100),
    QUANTIDADE NUMBER(10) NOT NULL,
    VEGETARIANO CHAR(1) NOT NULL,
    TAMANHO CHAR(1) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    PRECO NUMBER(7,2) NOT NULL,
    PRIMARY KEY (ID_PRODUTO)
);

CREATE SEQUENCE SEQ_PRODUTO
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;
