CREATE TABLE USUARIO_ROLE_CARGO(
	ID_USUARIO NUMBER(10) NOT NULL,
	ID_ROLE NUMBER(10) NOT NULL,
	PRIMARY KEY(ID_USUARIO,ID_ROLE),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY(ID_ROLE) REFERENCES CARGO (ID_ROLE)
);

