
CREATE TABLE USUARIO (
	ID_USUARIO NUMBER(10,0) NOT NULL,
	LOGIN VARCHAR2(50) NOT NULL,
	SENHA VARCHAR2(100) NOT NULL,
	ID_ROLE NUMBER(10,0) NOT NULL,
	PRIMARY KEY (ID_USUARIO),
	FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE)
);
CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;